spring.application.name=pharmacy-backend

# Database (update with your local Postgres credentials)
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmacy_db
spring.datasource.username=postgres
spring.datasource.password=678678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=change_this_to_a_long_random_secret_key_before_production_use
jwt.expiration-ms=86400000

server.port=8080
